# Generated by Django 3.1.4 on 2021-03-23 12:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecguyz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='imageback',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latest',
            name='imageback',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trending',
            name='imageback',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
