# Generated by Django 3.1.4 on 2021-03-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecguyz', '0002_auto_20210323_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='image',
        ),
        migrations.RemoveField(
            model_name='featured',
            name='imageback',
        ),
        migrations.RemoveField(
            model_name='latest',
            name='imageback',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='imageback',
        ),
    ]
