# Generated by Django 3.1.4 on 2021-03-25 00:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecguyz', '0003_auto_20210325_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
