# Generated by Django 3.1.4 on 2021-03-25 00:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecguyz', '0004_trending_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
