# Generated by Django 3.1.4 on 2021-03-25 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecguyz', '0005_auto_20210325_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='image',
        ),
    ]
