# Generated by Django 3.1.4 on 2021-04-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecguyz', '0007_trending_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='image',
        ),
    ]
