# Generated by Django 3.1.4 on 2021-04-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecguyz', '0009_trending_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='image',
            field=models.CharField(blank='True', max_length=2343),
        ),
        migrations.AddField(
            model_name='featured',
            name='image',
            field=models.CharField(blank='True', max_length=2343),
        ),
        migrations.AddField(
            model_name='latest',
            name='image',
            field=models.CharField(blank='True', max_length=2343),
        ),
    ]
